# Generated by Django 5.2.3 on 2025-07-27 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vault', '0004_loginactivity_securevaultitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='nominee',
            name='accessible_files',
            field=models.ManyToManyField(blank=True, related_name='accessible_nominees', to='Vault.uploadedfile'),
        ),
        migrations.AddField(
            model_name='nominee',
            name='accessible_vault_items',
            field=models.ManyToManyField(blank=True, related_name='accessible_nominees', to='Vault.securevaultitem'),
        ),
    ]
