# Generated by Django 5.2.3 on 2025-07-31 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vault', '0005_nominee_accessible_files_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='nominees',
            field=models.ManyToManyField(blank=True, related_name='accessible_uploaded_files', to='Vault.nominee'),
        ),
        migrations.AlterField(
            model_name='nominee',
            name='accessible_files',
            field=models.ManyToManyField(blank=True, related_name='accessible_nominees_files', to='Vault.uploadedfile'),
        ),
        migrations.AlterField(
            model_name='nominee',
            name='accessible_vault_items',
            field=models.ManyToManyField(blank=True, related_name='accessible_nominees_vault_items', to='Vault.securevaultitem'),
        ),
    ]
