# Generated by Django 5.2.3 on 2025-08-05 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vault', '0008_userprofile_account_timeout_minutes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='last_activity',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
