# Generated by Django 5.2.3 on 2025-08-07 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vault', '0009_alter_userprofile_last_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='inactivity_email_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_inactivity_email',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
